const region = {
    ID: 'Indonesia',
    US: 'United States',
    IN: 'India',
    JP: 'Japan',
    KR: 'South Korea',
    CN: 'China',
    DE: 'Germany',
    FR: 'France',
    GB: 'United Kingdom',
    BR: 'Brazil',
    RU: 'Russia',
    IT: 'Italy',
    ES: 'Spain',
    AU: 'Australia',
    CA: 'Canada',
    MX: 'Mexico',
    AR: 'Argentina',
    ZA: 'South Africa',
    EG: 'Egypt',
    NG: 'Nigeria',
    KE: 'Kenya',
    GH: 'Ghana',
    TR: 'Turkey',
    SA: 'Saudi Arabia',
    IR: 'Iran',
    PK: 'Pakistan',
    BD: 'Bangladesh',
    VN: 'Vietnam',
    TH: 'Thailand',
    MY: 'Malaysia',
    PH: 'Philippines',
    SG: 'Singapore',
    HK: 'Hong Kong',
    TW: 'Taiwan',
    LK: 'Sri Lanka',
    NP: 'Nepal',
    MM: 'Myanmar',
    KH: 'Cambodia',
    LA: 'Laos',
    NZ: 'New Zealand',
    PL: 'Poland',
    NL: 'Netherlands',
    BE: 'Belgium',
    CH: 'Switzerland',
    SE: 'Sweden',
    NO: 'Norway',
    DK: 'Denmark',
    FI: 'Finland',
    AT: 'Austria',
    PT: 'Portugal',
    GR: 'Greece',
    HU: 'Hungary',
    CZ: 'Czech Republic',
    SK: 'Slovakia',
    RO: 'Romania',
    BG: 'Bulgaria',
    UA: 'Ukraine',
    BY: 'Belarus',
    KZ: 'Kazakhstan',
    UZ: 'Uzbekistan',
    IQ: 'Iraq',
    SY: 'Syria',
    JO: 'Jordan',
    LB: 'Lebanon',
    IL: 'Israel',
    OM: 'Oman',
    QA: 'Qatar',
    AE: 'United Arab Emirates',
    BH: 'Bahrain',
    KW: 'Kuwait',
    YE: 'Yemen',
    MA: 'Morocco',
    DZ: 'Algeria',
    TN: 'Tunisia',
    SD: 'Sudan',
    ET: 'Ethiopia',
    UG: 'Uganda',
    TZ: 'Tanzania',
    CD: 'Democratic Republic of the Congo',
    CM: 'Cameroon',
    CI: 'Ivory Coast',
    SN: 'Senegal',
    MG: 'Madagascar',
    AO: 'Angola',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
    MZ: 'Mozambique',
    BW: 'Botswana',
    NA: 'Namibia',
    MW: 'Malawi',
    LS: 'Lesotho',
    SZ: 'Eswatini',
    GQ: 'Equatorial Guinea',
    GA: 'Gabon',
    CG: 'Republic of the Congo',
    DJ: 'Djibouti',
    ER: 'Eritrea',
    SO: 'Somalia',
    RW: 'Rwanda',
    BI: 'Burundi',
    SL: 'Sierra Leone',
    LR: 'Liberia',
    GM: 'Gambia',
    CU: 'Cuba',
    VE: 'Venezuela',
    CO: 'Colombia',
    PE: 'Peru',
    CL: 'Chile',
    BO: 'Bolivia',
    PY: 'Paraguay',
    UY: 'Uruguay',
    CR: 'Costa Rica',
    PA: 'Panama',
    GT: 'Guatemala',
    HN: 'Honduras',
    SV: 'El Salvador',
    NI: 'Nicaragua',
    JM: 'Jamaica',
    HT: 'Haiti',
    DO: 'Dominican Republic',
    TT: 'Trinidad and Tobago',
    BB: 'Barbados',
    AG: 'Antigua and Barbuda',
    BS: 'Bahamas',
    GD: 'Grenada',
    KN: 'Saint Kitts and Nevis',
    LC: 'Saint Lucia',
    VC: 'Saint Vincent and the Grenadines',
    FJ: 'Fiji',
    PG: 'Papua New Guinea',
    SB: 'Solomon Islands',
    WS: 'Samoa',
    TO: 'Tonga',
    TV: 'Tuvalu',
    VU: 'Vanuatu',
    KI: 'Kiribati',
    NR: 'Nauru',
    MH: 'Marshall Islands',
    FM: 'Federated States of Micronesia',
    PW: 'Palau'
};

module.exports = region;